[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "algoflex"
version = "1.1.1"
description = "Algoflex - An algorithm practice TUI"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
authors = [{name = "ndero", email = "jnderoh@gmail.com"}]
dependencies = [
  "textual[syntax]>=3.5.0",
]

[project.scripts]
algoflex = "algoflex.app:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
algoflex = [
  "questions/data/**/*",
]

[dependency-groups]
dev = [
    "pre-commit>=3.5.0",
    "pytest>=8.3.5",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.1",
]